Post.create(title: 'My first title', author: 'Lia Kitamura', description: 'Kenny G is crazy')
Post.create(title: 'My second title', author: 'Lia Kitamura', description: 'Kenny G is crazy')
Post.create(title: 'My third title', author: 'Lia Kitamura', description: 'Kenny G is crazy')
Post.create(title: 'My fourth title', author: 'Lia Kitamura', description: 'Kenny G is crazy')
Post.create(title: 'My fifth title', author: 'Lia Kitamura', description: 'Kenny G is crazy')
